name: CI
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # You may pin to the exact commit or the version.
      - uses: piotrpawlaczek/python-blacken@v20.8b1
        with:
          # File or directory to run black on.
          path: . # optional, default is .
          # The number of characters allowed per line.
          line-length: 81 # optional, default is 81
  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install -r requirements.txt -r test-requirements.txt
          pip install -e .
          pytest tests/
