name: CI
on: [push]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  lint:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: Python Blacken
        # You may pin to the exact commit or the version.
        # uses: piotrpawlaczek/python-blacken@00da49d5262ea8408aa006873de629fef9fc9dd1
        uses: piotrpawlaczek/python-blacken@v20.8b1
        with:
          # File or directory to run black on.
          path: . # optional, default is .
          # The number of characters allowed per line.
          line-length: 81 # optional, default is 81
  run_tests:
    runs-on: ubuntu-latest
    needs: [checkout, lint]
    steps:
    - name: Install in editable mode
      run: |
        pip install -r requirements.txt -r test-requirements.txt
        pip install -e .
    - name: Run tests
      run: pytest tests/
