name: CI
on: [push]
jobs:
  greet_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: SvoONs/greet_dev@main
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install ruff
      - run: | 
          ruff check .

  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install -r requirements.txt -r test-requirements.txt
          pip install -e .
          pytest tests/
